### PR TITLE
Smooth helmet

### PR DESCRIPTION
**Pull request by alexrockhill**
Uses a UV map to create MEG helmet image. This is done by unwrapping the helmet in 2D UV space, then making an image where every vertex above threshold adds a 2D symmetric Gaussian with a standard deviation equal to it's nearest neighbor.

To do:

1. The UV map causes stretching so even though the size of the Guassian is corrected by the nearest neighbor, the map would be more accurate if the Guassian was not symmetrical if neighbors in one direction were farther. (This might be okay as is, this would be a pretty involved fix).

2. I was able to display the texture using the node display:

screen shot 2018-11-03 at 9 14 07 pm

This needs to be added to the default MEG helmet or incorporated in another way which would probably be in src/mmvt_addon/coloring_pannel around line 1102.

3. Even with the node display as it was, the image is only visible in material or rendered view, not in solid view. When Plot MEG Helmet is called it could switch to rendered or maybe someone knows how to have the image appear on the solid.

default_24 jpeg_1
default_24 jpeg_0

### CODE REVIEW

**Comment by pelednoam** [comment]
Great!!!
Just small issues:
1) Why did you import matplotlib? Try to avoid matplotlib in Blender, and if you must use it, import it in a try block
2) Please change the variables and functions names to my_variableinstead of MyVariable

**Comment by alexrockhill** [comment]
The UV Texture is made from an image that is generated by matplotlib. If there is another way to generate an image using Blender built-in functions we could do that too.

**Comment by pelednoam** [comment]
Maybe using the bpy.data.images.new()? Like [here](https://blender.stackexchange.com/questions/14097/set-active-image-node-with-python/14115#14115)?
If possible, we should avoid saving figures using matplotlib inside Blender.

**Comment by alexrockhill** [comment]
So why I used matplotlib is for the colormap. It might take fairly extensive rewriting because the calc_colors as is just takes the valid_verts but instead you would want to set the scale and then get a color for every pixel of the UV map with the 2D Gaussian gradient. I'll give it a try...

**Pull request merged**
